import os

KEY_BINANCE = os.getenv('KEY_BINANCE')
SECRET_BINANCE = os.getenv('KEY_BINANCE')
API_BINANCE = os.getenv('API_BINANCE')
API_EXCHANGE_BINANCE = os.getenv('API_EXCHANGE_BINANCE')

KEY_TEST_BINANCE = os.getenv('KEY_TEST_BINANCE')
SECRET_TEST_BINANCE = os.getenv('SECRET_TEST_BINANCE')
API_TEST_BINANCE = os.getenv('API_TEST_BINANCE')
